### ISSUE TITLE
FileNotFoundError:  No such file or directory: 'simlarity.json'

### ISSUE THREAD

**Issue by Hai333** [skJack/DiffusionFake#2]
When generate training weights: python generate_weight.py
![QQ_1729683862149](https://github.com/user-attachments/assets/f6a869ae-3a7a-48b8-a120-7fc097b6f12d)
Besides, in your requirements.txt,  versions pytorch and xformers do not match

**Comment by chenyq347** [comment]
excuse me，have you solved the version problems yet? I also have these same question

**Comment by muliyangm** [comment]
Have you solved the issue of `similarity.json`? Do you have any thoughts to share? Thank you!
